name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gestor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Verificar codigo
        run: go vet ./...

      - name: Compilar
        run: go build ./...

      - name: Build imagem Docker
        run: >
          docker build
          -t ${{ env.REGISTRY }}/${{ secrets.GH_USER }}/${{ env.IMAGE_NAME }}:latest
          -f Dockerfile .

      - name: Login GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          echo "${{ secrets.GH_TOKEN }}" | docker login ${{ env.REGISTRY }} \
            -u ${{ secrets.GH_USER }} --password-stdin

      - name: Push imagem
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ env.REGISTRY }}/${{ secrets.GH_USER }}/${{ env.IMAGE_NAME }}:latest
